services:
  localstack:
    container_name: localstack-pro
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - SERVICES=s3,sqs,secretsmanager
      - DEBUG=${DEBUG:-0}
      - AWS_ACCESS_KEY_ID=test # default AWS credentials
      - AWS_SECRET_ACCESS_KEY=test # default AWS credentials
      - PERSISTENCE=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack" # LocalStack data volume
      - "/var/run/docker.sock:/var/run/docker.sock"
